name:                choice2
version:             0.1.0.0

dependencies:
  - base >= 4.7 && < 5

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

language: GHC2021

default-extensions:
 - OverloadedStrings
 - LambdaCase
 - DuplicateRecordFields

library:
  source-dirs: src
  dependencies:
    - bytestring
    - hypertypes
    - generic-constraints
    - template-haskell
    - mtl
    - lens
    - unordered-containers
    - containers
    - hashable
    - random
    - transformers
